import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

// ESLint 9 flat config. eslint-config-next v16 ships flat-config arrays
// directly, so no FlatCompat shim is needed.
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      "public/**",
      // Generated by the shadcn CLI — regenerating would wipe any fixes, so
      // these are linted by upstream, not by us.
      "src/components/ui/**",
      "src/hooks/use-toast.ts",
    ],
  },
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      // Surfaces leftovers as we build out screens rather than at the end.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
