import type {
  Patient,
  Appointment,
  DoctorAvailability,
  Message,
  PatientRequest,
  Doctor,
} from "./types";

// ---------------------------------------------------------------------------
// Doctors
// ---------------------------------------------------------------------------

export const doctors: Doctor[] = [
  { id: "doc-1", fullName: "Dr. Akosua Mensah", specialty: "Specialist Physician" },
];

// ---------------------------------------------------------------------------
// Patients — 16, varied preferred channels, some missing email.
// ---------------------------------------------------------------------------

export const patients: Patient[] = [
  {
    id: "p-001",
    fullName: "Kwabena Owusu",
    phone: "+233 24 123 4567",
    whatsappNumber: "+233 24 123 4567",
    email: "kwabena.owusu@gmail.com",
    dateOfBirth: "1987-03-14",
    preferredChannel: "whatsapp",
    registeredDate: "2024-01-08",
    notes: "Prefers morning appointments.",
  },
  {
    id: "p-002",
    fullName: "Ama Serwaa",
    phone: "+233 20 987 6543",
    whatsappNumber: "+233 20 987 6543",
    email: "ama.serwaa@yahoo.com",
    dateOfBirth: "1992-07-22",
    preferredChannel: "whatsapp",
    registeredDate: "2024-01-15",
  },
  {
    id: "p-003",
    fullName: "Yaw Boateng",
    phone: "+233 27 555 0118",
    dateOfBirth: "1975-11-02",
    preferredChannel: "sms",
    registeredDate: "2024-02-01",
    notes: "SMS-only — no email on file.",
  },
  {
    id: "p-004",
    fullName: "Abena Dapaah",
    phone: "+233 24 444 7788",
    whatsappNumber: "+233 24 444 7788",
    email: "abena.dapaah@outlook.com",
    dateOfBirth: "1990-05-30",
    preferredChannel: "email",
    registeredDate: "2024-02-12",
  },
  {
    id: "p-005",
    fullName: "Kofi Asante",
    phone: "+233 20 332 1100",
    whatsappNumber: "+233 20 332 1100",
    dateOfBirth: "1983-09-18",
    preferredChannel: "sms",
    registeredDate: "2024-02-20",
  },
  {
    id: "p-006",
    fullName: "Esi Mensimah",
    phone: "+233 26 901 2233",
    whatsappNumber: "+233 26 901 2233",
    email: "esi.mensimah@gmail.com",
    dateOfBirth: "1995-12-05",
    preferredChannel: "whatsapp",
    registeredDate: "2024-03-02",
  },
  {
    id: "p-007",
    fullName: "Kojo Frimpong",
    phone: "+233 24 667 8899",
    whatsappNumber: "+233 24 667 8899",
    email: "kojo.frimpong@gmail.com",
    dateOfBirth: "1978-04-11",
    preferredChannel: "email",
    registeredDate: "2024-03-10",
  },
  {
    id: "p-008",
    fullName: "Adwoa Nyarko",
    phone: "+233 27 220 4455",
    dateOfBirth: "2000-08-19",
    preferredChannel: "sms",
    registeredDate: "2024-03-22",
  },
  {
    id: "p-009",
    fullName: "Ekow Mensah",
    phone: "+233 20 778 1122",
    whatsappNumber: "+233 20 778 1122",
    email: "ekow.mensah@hotmail.com",
    dateOfBirth: "1989-01-27",
    preferredChannel: "whatsapp",
    registeredDate: "2024-04-05",
  },
  {
    id: "p-010",
    fullName: "Akua Tweneboah",
    phone: "+233 24 556 3300",
    whatsappNumber: "+233 24 556 3300",
    email: "akua.tweneboah@gmail.com",
    dateOfBirth: "1993-06-14",
    preferredChannel: "email",
    registeredDate: "2024-04-18",
  },
  {
    id: "p-011",
    fullName: "Nana Yaw Darko",
    phone: "+233 26 414 9988",
    whatsappNumber: "+233 26 414 9988",
    dateOfBirth: "1970-02-08",
    preferredChannel: "sms",
    registeredDate: "2024-05-01",
    notes: "Hypertension follow-up.",
  },
  {
    id: "p-012",
    fullName: "Afia Pokuaa",
    phone: "+233 20 880 6677",
    whatsappNumber: "+233 20 880 6677",
    email: "afia.pokuaa@yahoo.com",
    dateOfBirth: "1998-10-23",
    preferredChannel: "whatsapp",
    registeredDate: "2024-05-14",
  },
  {
    id: "p-013",
    fullName: "Kwesi Appiah",
    phone: "+233 24 112 5566",
    whatsappNumber: "+233 24 112 5566",
    email: "kwesi.appiah@gmail.com",
    dateOfBirth: "1985-07-09",
    preferredChannel: "email",
    registeredDate: "2024-06-03",
  },
  {
    id: "p-014",
    fullName: "Eunice Adjei",
    phone: "+233 27 334 8821",
    dateOfBirth: "1996-03-17",
    preferredChannel: "sms",
    registeredDate: "2024-06-20",
  },
  {
    id: "p-015",
    fullName: "Selorm Agbodzi",
    phone: "+233 24 990 0011",
    whatsappNumber: "+233 24 990 0011",
    email: "selorm.agbodzi@gmail.com",
    dateOfBirth: "1991-11-28",
    preferredChannel: "whatsapp",
    registeredDate: "2024-07-08",
  },
  {
    id: "p-016",
    fullName: "Mansa Asante-Boateng",
    phone: "+233 20 661 2200",
    whatsappNumber: "+233 20 661 2200",
    email: "mansa.ab@outlook.com",
    dateOfBirth: "1982-12-30",
    preferredChannel: "email",
    registeredDate: "2024-07-19",
  },
];

// ---------------------------------------------------------------------------
// Doctor availability — non-flat pattern.
// Mon: closed. Tue: morning only. Wed: full day. Thu: afternoon only.
// Fri: morning only. Sat: closed. Sun: closed.
// ---------------------------------------------------------------------------

export const doctorAvailability: DoctorAvailability[] = [
  { doctorId: "doc-1", dayOfWeek: 0, startTime: "00:00", endTime: "23:59", isAvailable: false }, // Sun
  { doctorId: "doc-1", dayOfWeek: 1, startTime: "00:00", endTime: "23:59", isAvailable: false }, // Mon — off
  { doctorId: "doc-1", dayOfWeek: 2, startTime: "08:00", endTime: "12:00", isAvailable: true },  // Tue AM
  { doctorId: "doc-1", dayOfWeek: 3, startTime: "08:00", endTime: "17:00", isAvailable: true },  // Wed all day
  { doctorId: "doc-1", dayOfWeek: 4, startTime: "13:00", endTime: "17:00", isAvailable: true },  // Thu PM only
  { doctorId: "doc-1", dayOfWeek: 5, startTime: "08:00", endTime: "12:00", isAvailable: true },  // Fri AM
  { doctorId: "doc-1", dayOfWeek: 6, startTime: "00:00", endTime: "23:59", isAvailable: false }, // Sat — off
];

// ---------------------------------------------------------------------------
// Appointments — past + future, all 5 statuses, enough missed + attended.
// Dates are relative to "today" so the prototype always has live data.
// ---------------------------------------------------------------------------

function isoOffset(daysFromToday: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + daysFromToday);
  return d.toISOString().slice(0, 10);
}

export const appointments: Appointment[] = [
  // Past — attended history
  {
    id: "a-1001",
    patientId: "p-001",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(-28),
    time: "09:00",
    durationMinutes: 30,
    status: "attended",
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: "a-1002",
    patientId: "p-004",
    doctorId: "doc-1",
    appointmentType: "Follow-up",
    date: isoOffset(-21),
    time: "10:30",
    durationMinutes: 30,
    status: "attended",
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: "a-1003",
    patientId: "p-006",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(-14),
    time: "08:30",
    durationMinutes: 45,
    status: "attended",
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  // Past — missed (populate follow-up list)
  {
    id: "a-1004",
    patientId: "p-003",
    doctorId: "doc-1",
    appointmentType: "Follow-up",
    date: isoOffset(-7),
    time: "09:30",
    durationMinutes: 30,
    status: "missed",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    notes: "No-show, no prior notice.",
  },
  {
    id: "a-1005",
    patientId: "p-008",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(-5),
    time: "14:00",
    durationMinutes: 30,
    status: "missed",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "a-1006",
    patientId: "p-011",
    doctorId: "doc-1",
    appointmentType: "Hypertension Review",
    date: isoOffset(-3),
    time: "15:30",
    durationMinutes: 30,
    status: "missed",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  // Past — rescheduled
  {
    id: "a-1007",
    patientId: "p-002",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(-10),
    time: "11:00",
    durationMinutes: 30,
    status: "rescheduled",
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    notes: "Patient rescheduled to next week.",
  },
  // Today — confirmed
  {
    id: "a-2001",
    patientId: "p-005",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(0),
    time: "09:00",
    durationMinutes: 30,
    status: "confirmed",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "a-2002",
    patientId: "p-009",
    doctorId: "doc-1",
    appointmentType: "Follow-up",
    date: isoOffset(0),
    time: "10:30",
    durationMinutes: 30,
    status: "confirmed",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "a-2003",
    patientId: "p-012",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(0),
    time: "14:00",
    durationMinutes: 45,
    status: "booked",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  // Future — booked / confirmed mix
  {
    id: "a-2004",
    patientId: "p-007",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(2),
    time: "08:30",
    durationMinutes: 30,
    status: "booked",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "a-2005",
    patientId: "p-010",
    doctorId: "doc-1",
    appointmentType: "Follow-up",
    date: isoOffset(3),
    time: "11:00",
    durationMinutes: 30,
    status: "confirmed",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "a-2006",
    patientId: "p-013",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(5),
    time: "09:30",
    durationMinutes: 30,
    status: "booked",
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "a-2007",
    patientId: "p-015",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(7),
    time: "10:00",
    durationMinutes: 45,
    status: "booked",
    createdAt: new Date().toISOString(),
  },
  {
    id: "a-2008",
    patientId: "p-016",
    doctorId: "doc-1",
    appointmentType: "Follow-up",
    date: isoOffset(9),
    time: "14:30",
    durationMinutes: 30,
    status: "confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "a-2009",
    patientId: "p-014",
    doctorId: "doc-1",
    appointmentType: "Consultation",
    date: isoOffset(12),
    time: "15:00",
    durationMinutes: 30,
    status: "booked",
    createdAt: new Date().toISOString(),
  },
];

// ---------------------------------------------------------------------------
// Messages — 17 entries, all types/channels, at least one failed.
// ---------------------------------------------------------------------------

export const messages: Message[] = [
  {
    id: "m-001",
    patientId: "p-001",
    appointmentId: "a-1001",
    channel: "whatsapp",
    type: "confirmation",
    sentAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Your appointment on {date} at 09:00 is confirmed. Reply to confirm.",
  },
  {
    id: "m-002",
    patientId: "p-001",
    appointmentId: "a-1001",
    channel: "whatsapp",
    type: "reminder",
    sentAt: new Date(Date.now() - 29 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Reminder: appointment tomorrow at 09:00 with Dr. Mensah.",
  },
  {
    id: "m-003",
    patientId: "p-004",
    appointmentId: "a-1002",
    channel: "email",
    type: "confirmation",
    sentAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Appointment confirmed for {date} at 10:30.",
  },
  {
    id: "m-004",
    patientId: "p-006",
    appointmentId: "a-1003",
    channel: "whatsapp",
    type: "reminder",
    sentAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Reminder: appointment tomorrow at 08:30.",
  },
  {
    id: "m-005",
    patientId: "p-003",
    appointmentId: "a-1004",
    channel: "sms",
    type: "reminder",
    sentAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    deliveryStatus: "sent",
    contentPreview: "Reminder: appointment tomorrow at 09:30.",
  },
  {
    id: "m-006",
    patientId: "p-003",
    appointmentId: "a-1004",
    channel: "sms",
    type: "follow-up",
    sentAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    deliveryStatus: "failed",
    contentPreview: "You missed your appointment. Please call to reschedule.",
  },
  {
    id: "m-007",
    patientId: "p-008",
    appointmentId: "a-1005",
    channel: "sms",
    type: "reminder",
    sentAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Reminder: appointment tomorrow at 14:00.",
  },
  {
    id: "m-008",
    patientId: "p-008",
    appointmentId: "a-1005",
    channel: "sms",
    type: "follow-up",
    sentAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    deliveryStatus: "sent",
    contentPreview: "Missed appointment — please contact us to reschedule.",
  },
  {
    id: "m-009",
    patientId: "p-011",
    appointmentId: "a-1006",
    channel: "sms",
    type: "follow-up",
    sentAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Missed hypertension review. Please book a new slot.",
  },
  {
    id: "m-010",
    patientId: "p-002",
    appointmentId: "a-1007",
    channel: "whatsapp",
    type: "confirmation",
    sentAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Appointment confirmed for {date} at 11:00.",
  },
  {
    id: "m-011",
    patientId: "p-005",
    appointmentId: "a-2001",
    channel: "sms",
    type: "confirmation",
    sentAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Your appointment today at 09:00 is confirmed.",
  },
  {
    id: "m-012",
    patientId: "p-009",
    appointmentId: "a-2002",
    channel: "whatsapp",
    type: "reminder",
    sentAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Reminder: appointment today at 10:30.",
  },
  {
    id: "m-013",
    patientId: "p-007",
    appointmentId: "a-2004",
    channel: "email",
    type: "confirmation",
    sentAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    deliveryStatus: "sent",
    contentPreview: "Appointment booked for {date} at 08:30. Please confirm.",
  },
  {
    id: "m-014",
    patientId: "p-010",
    appointmentId: "a-2005",
    channel: "email",
    type: "reminder",
    sentAt: new Date().toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Reminder: appointment on {date} at 11:00.",
  },
  {
    id: "m-015",
    patientId: "p-004",
    channel: "email",
    type: "birthday",
    sentAt: new Date().toISOString(),
    deliveryStatus: "delivered",
    contentPreview: "Happy birthday from Rophe Specialist Care!",
  },
  {
    id: "m-016",
    patientId: "p-016",
    appointmentId: "a-2008",
    channel: "email",
    type: "confirmation",
    sentAt: new Date().toISOString(),
    deliveryStatus: "sent",
    contentPreview: "Appointment confirmed for {date} at 14:30.",
  },
  {
    id: "m-017",
    patientId: "p-014",
    appointmentId: "a-2009",
    channel: "sms",
    type: "reminder",
    sentAt: new Date().toISOString(),
    deliveryStatus: "failed",
    contentPreview: "Reminder: appointment on {date} at 15:00. (delivery failed — retry queued)",
  },
];

// ---------------------------------------------------------------------------
// Pending requests — 3, mix of reschedule + cancellation.
// ---------------------------------------------------------------------------

export const patientRequests: PatientRequest[] = [
  {
    id: "r-001",
    appointmentId: "a-2004",
    patientId: "p-007",
    requestType: "reschedule",
    requestedDate: isoOffset(6),
    requestedTime: "10:00",
    reason: "Work commitment at original time.",
    status: "pending",
  },
  {
    id: "r-002",
    appointmentId: "a-2002",
    patientId: "p-009",
    requestType: "reschedule",
    requestedDate: isoOffset(4),
    requestedTime: "09:00",
    reason: "",
    status: "pending",
  },
  {
    id: "r-003",
    appointmentId: "a-2003",
    patientId: "p-012",
    requestType: "cancellation",
    reason: "Feeling better, no longer needed.",
    status: "pending",
  },
];
